services:
  postgres:
    image: postgres:16.3
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: ecom
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d

  backend:
    build: .
    container_name: backend
    restart: always
    ports:
      - "8080:8080"  
    env_file:
      - .env  
    depends_on:
      - postgres
    volumes:
      - .env:/root/.env  

volumes:
  postgres_data:
