name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure gcloud CLI
        run: gcloud config set project ${{ secrets.PROJECT_ID }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-service \
            --image=docker.io/oleh01/golang-ecom \
            --platform=managed \
            --region=europe-west1 \
            --allow-unauthenticated \
            --add-cloudsql-instances=${{ secrets.INSTANCE_CONNECTION_NAME }} \
            --set-env-vars="DB_HOST=/cloudsql/${{ secrets.INSTANCE_CONNECTION_NAME }},DB_USER=myuser,DB_PASSWORD=mypassword,SERVER_ADDR=8080"
