name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -o bin/ecom cmd/main.go

    - name: Test
      run: go test -v ./...

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: oleh01/golang-ecom
        tag: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy my-service \
          --image=docker.io/oleh01/golang-ecom:latest \
          --platform=managed \
          --region=europe-west1 \
          --allow-unauthenticated \
          --add-cloudsql-instances=skillful-elf-449919-q5:europe-central2:postgres \
          --set-env-vars="\
            SERVER_ADDR=${{ secrets.SERVER_ADDR }},\
            DB_ADDR=${{ secrets.DB_ADDR }},\
            JWT_EXPIRATION_SECONDS=${{ secrets.JWT_EXPIRATION_SECONDS }},\
            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" \
          --project=skillful-elf-449919-q5
